/*
Copyright 2022 The Clusternet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package utils

import "k8s.io/apimachinery/pkg/version"

const (
	// KubeV1240 indicates the version of Kubernetes v1.24.0
	// This should be "v1.24.0-alpha.4", but it does not tolerate v1.24.0.
	KubeV1240 = "v1.24.0"
)

// SATokenAutoGenerated is used to indicate whether secret-based service account token can be auto generated
func SATokenAutoGenerated(kubeServerVersion string) bool {
	return version.CompareKubeAwareVersionStrings(kubeServerVersion, KubeV1240) > 0
}
