/*
Copyright 2022 The Clusternet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package utils

import (
	"testing"
)

func TestSATokenAutoGenerated(t *testing.T) {
	tests := []struct {
		name              string
		kubeServerVersion string
		want              bool
	}{
		// no auto-generation of secret-based service account token
		{
			kubeServerVersion: KubeV1240,
			want:              false,
		},
		{
			kubeServerVersion: "v1.24.0",
			want:              false,
		},
		{
			kubeServerVersion: "v1.24.1",
			want:              false,
		},
		{
			kubeServerVersion: "v1.24.6+k3s1",
			want:              false,
		},
		{
			kubeServerVersion: "v1.24.0-rc1+k3s1",
			want:              false,
		},
		{
			kubeServerVersion: "v1.25.0",
			want:              false,
		},

		// auto-generation of legacy secret-based service account token
		{
			kubeServerVersion: "v1.23.1",
			want:              true,
		},
		{
			kubeServerVersion: "v1.23.6+k3s1",
			want:              true,
		},
		{
			kubeServerVersion: "v1.23.12-rc1+k3s1",
			want:              true,
		},
		{
			kubeServerVersion: "v1.22.10",
			want:              true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := SATokenAutoGenerated(tt.kubeServerVersion); got != tt.want {
				t.Errorf("kubeServerVersion %s wants %v", tt.kubeServerVersion, tt.want)
			}
		})
	}
}
