apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: node-feature-discovery
  namespace: default
spec:
  repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  chart: node-feature-discovery
  version: 0.11.2
  targetNamespace: node-feature-discovery
