run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - structcheck
    - goimports
    - gosimple
    - gofmt
    - misspell
    - unparam
    - unconvert
    - unused
    - govet
    - errcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - unparam