apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: mysql
  namespace: default
spec:
  repo: oci://myoci.registry.com:5000/helm-charts
  chart: mysql
  version: 9.2.0
  targetNamespace: abc
