apiVersion: v1
kind: Namespace
metadata:
  name: baz
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: baz
  labels:
    clusternet-app: multi-cluster-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              memory: 256Mi
              cpu: 500m
        - name: redis # only for testing
          image: redis:6.2
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              memory: 256Mi
              cpu: 500m
