apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: dynamic-dividing-scheduling-demo
  namespace: default
spec:
  schedulingBySubGroup: true
  subscribers: # defines the clusters to be distributed to
    - clusterAffinity:
        matchLabels:
          region: ap-shanghai
      subGroupStrategy:
        minClusters: 1 # the number of pick cluster in every group
    - clusterAffinity:
        matchLabels:
          region: ap-beijing
      subGroupStrategy:
        minClusters: 1 # the number of pick cluster in every group
  schedulingStrategy: Dividing
  dividingScheduling:
    type: Dynamic
    dynamicDividing:
      strategy: Spread # currently we only support Spread dividing strategy
  feeds: # defines all the resources to be deployed with
    - apiVersion: v1
      kind: Namespace
      name: qux
    - apiVersion: v1
      kind: Service
      name: my-nginx-svc
      namespace: qux
    - apiVersion: apps/v1 # with a total of 6 replicas
      kind: Deployment
      name: my-nginx
      namespace: qux
