apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: mysql-global-overrides-demo
spec:
  # Priority is an integer defining the relative importance of this Globalization compared to others.
  # Lower numbers are considered lower priority.
  # Override values in lower Globalization will be overridden by those in higher Globalization.
  # (Optional) Default priority is 500.
  priority: 600
  feed:
    apiVersion: apps.clusternet.io/v1alpha1
    kind: HelmChart
    name: mysql
    namespace: default
  overrides: # defines all the overrides to be processed with
    - name: override-commonLabels
      type: Helm # This can only be "Helm" for HelmRelease Values.
      # Value is a YAML/JSON format patch that overrides values to current Helm chart defined by feed.
      # And the value here is exactly the same as file "values.yaml".
      # This override patches parameter commonLabels on Mysql chart.
      value: |-
        commonLabels:
          clusternet.io/override-by: clusternet-hub
          some-label: some-value
    - name: disable-pvc-usage
      type: Helm # This can only be "Helm" for HelmRelease Values.
      # Value is a YAML/JSON format patch that overrides values to current Helm chart defined by feed.
      # And the value here is exactly the same as file "values.yaml".
      # This override disables using PersistentVolumeClaim on MySQL primary replicas.
      # The value here can also be in json format.
      value: '{"primary":{"persistence":{"enabled":false}}}'
    - name: update-helm-chart-version
      overrideChart: true # This is a flag to indicate that this override is for HelmChart CR.
      type: Helm # This can only be "Helm" for HelmChart.
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # And the value here will be synchronized to HelmRelease.
      # This override update the version of Helm chart defined by feed.
      value: |-
        spec:
          version: 9.1.0
    - name: add-helm-chart-labels
      type: Helm # This can only be "Helm" for HelmChart.
      overrideChart: true # This is a flag to indicate that this override is for HelmChart CR.
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # And the value here will be synchronized to HelmRelease.
      # This override adds or updates some labels.
      value: |-
        metadata:
          labels:
            some-label: some-value
            another-label: another-value
---

apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: nginx-global-overrides-demo
spec:
  # Priority is an integer defining the relative importance of this Globalization compared to others.
  # Lower numbers are considered lower priority.
  # Override values in lower Globalization will be overridden by those in higher Globalization.
  # (Optional) Default priority is 500.
  priority: 600
  feed:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
    namespace: foo
  overrides: # defines all the overrides to be processed with
    - name: add-update-labels
      type: MergePatch
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # This override adds or updates some labels.
      value: |-
        metadata:
          labels:
            some-label: some-value
            another-label: another-value
    - name: remove-labels
      type: MergePatch
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # This override removes some labels.
      # The value here can also be in json format.
      value: '{"metadata":{"labels":{"another-label":null,"some-other-label":null}}}'
