kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-bootstrap-use
  namespace: clusternet-system

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-bootstrap-use
  namespace: clusternet-system
  annotations:
    kubernetes.io/service-account.name: cluster-bootstrap-use
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusternet:system:bootstrapping:sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusternet:system:bootstrapping
subjects:
  - kind: ServiceAccount
    name: cluster-bootstrap-use
    namespace: clusternet-system
