apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: configmap-demo
spec:
  subscribers:
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-id: dc91021d-2361-4f6d-a404-7c33b9e01118
  feeds:
    - apiVersion: v1
      kind: ConfigMap
      name: foo
      namespace: default

