apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: nginx
  namespace: default
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: nginx
  version: 8.5.4
  targetNamespace: abc
