apiVersion: apps.clusternet.io/v1alpha1
kind: Localization
metadata:
  name: mysql-loc
  namespace: clusternet-px5n9 # MUST BE THE SAME AS YOUR MANAGED CLUSTER's NAMESPACE!!!
spec:
  feed:
    apiVersion: apps.clusternet.io/v1alpha1
    kind: HelmChart
    name: mysql
    namespace: default
  overrides: # defines all the overrides to be process with
    - name: disablePersistenceAndChangeImage
      type: Helm
      # Value is a YAML format patch that override values to Helm chart.
      # This patch overrides parameter primary.persistence.enabled and image.tag on Mysql chart.
      value: |-
        primary:
          persistence:
            enabled: false
        image:
          tag: 8.0.26-debian-10-r39

---

apiVersion: apps.clusternet.io/v1alpha1
kind: Localization
metadata:
  name: nginx-loc
  namespace: clusternet-px5n9 # MUST BE THE SAME AS YOUR MANAGED CLUSTER's NAMESPACE!!!
spec:
  feed:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
    namespace: foo
  overrides: # defines all the overrides to be process with
    - name: scaleAndAddAnno
      type: JSONPatch
      # Value is a JSON format patch that provide JSONPatch to Kubernetes resources
      # This patch set the replicas field to 2 and add annotation foo=bar
      value: |-
        [
          {
            "path": "/spec/replicas",
            "value": "2",
            "op": "replace"
          },
          {
            "path": "/metadata/annotations",
            "value": {
              "foo":"bar"
            },
            "op": "add"
          }
        ]
    - name: changeImageAndContainerName
      type: JSONPatch
      # Value is a YAML format patch that provide JSONPatch to Kubernetes resources
      # This patch set the image and name of the first container
      value: |-
        - path: "/spec/template/spec/containers/0/image"
          value: "nginx:1.14.0-alpine"
          op: replace
        - path: "/spec/template/spec/containers/0/name"
          value: "nginx-container"
          op: replace

---

apiVersion: apps.clusternet.io/v1alpha1
kind: Localization
metadata:
  name: nginx-loc-lower-priority
  namespace: clusternet-px5n9 # MUST BE THE SAME AS YOUR MANAGED CLUSTER's NAMESPACE!!!
spec:
  # Priority is an integer defining the relative importance of this Localization compared to others. Lower numbers are considered lower priority. Optional.
  # Default priority is 500.
  priority: 300
  feed:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
    namespace: foo
  overrides: # defines all the overrides to be process with
    - name: scale
      type: JSONPatch
      # This patch want to set replicas field to 1.
      # But due to lower priority, the nginx-deployment's replicas will be override by nginx-loc above eventually.
      value: |-
        [
          {
            "path": "/spec/replicas",
            "value": "1",
            "op": "replace"
          }
        ]
