name: FOSSA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  fossa-key: cdfdc6e7b23f5026369e7a22767043ec # This is a public key only for pushing, it's safe here

jobs:
  build:
    if: github.repository_owner == 'clusternet'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go version
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - uses: fossas/fossa-action@main
        name: Scanning with FOSSA
        with:
          api-key: ${{ env.fossa-key }}
          branch: ${{ steps.branch-name.outputs.current_branch }}
      - uses: fossas/fossa-action@main
        name: Executing tests with FOSSA
        with:
          api-key: ${{ env.fossa-key }}
          run-tests: true
