name: Subrepo
on:
  push:
    branches:
      - main
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  repo-dispatching:
    if: github.repository_owner == 'clusternet'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - clusternet/apis
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          # A repo scoped GitHub Personal Access Token
          token: ${{ secrets.DOWNSTREAM_REPO_DISPATCH_TOKEN }}
          # The full name of the repository to send the dispatch.
          repository: ${{ matrix.repo }}
          # A custom webhook event name.
          event-type: sync-upstream
          # JSON payload with extra information about the webhook event that your action or worklow may use.
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
